name: joomla-external-login_devcontainer
services:
  joomla:
    build:
      context: ./joomla
    image: joomla:external-login
    volumes:
      - type: volume
        source: joomla_data
        target: /var/www/html
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/joomla/logs
        target: /var/www/html/administrator/logs
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}
        target: /workspace
        consistency: cached
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/php.ini
        target: /usr/local/etc/php/php.ini
        read_only: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.vscode
        target: /var/www/html/.vscode
        consistency: cached
    environment:
      JOOMLA_DB_HOST: ${JOOMLA_DB_HOST:-mysql}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD:-${MYSQL_ROOT_PASSWORD:-secret}}
      SSL_CERT_FILE: /run/secrets/ca.pem
    secrets:
      - ca.pem
    depends_on:
      - mysql
      - traefik
    external_links:
      - traefik:store.dev.local
      - traefik:www.dev.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.joomla.entrypoints=websecure
      - traefik.http.routers.joomla.rule=Host(`www.dev.local`)

  keycloak:
    build: ./keycloak
    image: keycloak:cas
    volumes:
      - type: volume
        source: keycloak_data
        target: /opt/keycloak/data
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/keycloak/export
        target: /opt/keycloak/data/export
        bind:
          create_host_path: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/keycloak/import
        target: /opt/keycloak/data/import
    # https://www.keycloak.org/server/configuration#_starting_keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      # https://www.keycloak.org/server/configuration
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/reverseproxy
      KC_PROXY_HEADERS: xforwarded
      # https://www.keycloak.org/server/all-config
      KC_HOSTNAME: auth.dev.local
      SSL_CERT_FILE: /run/secrets/ca.pem
    secrets:
      - ca.pem
    depends_on:
      - mysql
      - traefik
    external_links:
      - traefik:www.dev.local
      - traefik:auth.dev.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.openmage.entrypoints=websecure
      - traefik.http.routers.openmage.rule=Host(`auth.dev.local`)
      - traefik.http.services.openmage.loadbalancer.server.port=8080

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-joomla}
    ports:
      - 127.0.0.1:3306:3306

  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik
    networks:
      default:
        aliases:
          - auth.dev.local
          - www.dev.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/etc:/etc/traefik
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefik/dynamic/
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
      - 127.0.0.1:9090:8080
    secrets:
      - cert.pem
      - key.pem

secrets:
  ca.pem:
    file: .secrets/ca.pem
  cert.pem:
    file: .secrets/cert.pem
  key.pem:
    file: .secrets/key.pem

volumes:
  joomla_data: null
  mysql_data: null
  keycloak_data: null
